/********************************************************
 * Created by: The Hulk @ CloudRoute Solutions
 * Created Date: 01-04-2019.
 * Description: JobOrderWrapper
 ********************************************************/
public  class JobOrderWrapper {
    public Integer id ;
    public String title ;
    public String status ;
    public String description;
    public Association clientCorporation ;
    public Association clientContact ;
    public OwnerAssociation owner;
}